### ISSUE TITLE
Center "submit" button under Search and Zip text fields

### ISSUE THREAD

**Issue by taylorbasso** [taylorbasso/2450SoftwareEngineeringGroup#3]
We need to center the submit button that is currently underneath the zip and google search bars at the top of the page.

Also need to code some javascript to find out which text field is filled out (Is Zip filled in or is Search bar filled in?)

I suppose we could also add two submit buttons but that would be kind of messy. We can write some simple javascript to find out which field is filled out and then do an action accordingly.

**Comment by NicholasLambert** [comment]
Took out the submit button.
