### ISSUE TITLE
JS-Cookie for user Preferences

### ISSUE THREAD

**Issue by taylorbasso** [taylorbasso/2450SoftwareEngineeringGroup#6]
Remembering user prefs could be done by setting a cookie, so I'd recommend getting familiar with js-cookie  https://github.com/js-cookie/js-cookie

**Comment by sbenjam1n** [comment]
I'll get started on this.

**Comment by sbenjam1n** [comment]
So I ran into a few complications with this, but I should have this done by the end of today.
