### ISSUE TITLE
Integrate WeatherGet Javascript file

### ISSUE THREAD

**Issue by taylorbasso** [taylorbasso/2450SoftwareEngineeringGroup#8]
Integrate Steven's WeatherGet.js file so that we can:
1. Display Location
2. Display Temperature
3. Display Corresponding Weather Image

**Comment by sbenjam1n** [comment]
This should be done no later than Friday night.

**Comment by sbenjam1n** [comment]
Check my pull request, I've updated index and have added getWeather to the js file. 

Updating the html when the zip code is entered still needs to be done and I'm not sure where the forecast and location info are going, but at least everything can start to come together.

 I'd also suggest updating the names of the weather icons in the png file to match the openweathermap condition code ids here: 

http://openweathermap.org/weather-conditions

It would really simplify the code and allow us to use more of those images. For example, 'sunny-day.png' becomes '800.png'

**Comment by damooch** [comment]
I guess my only concern with renaming things to match a weather condition code makes it so we constantly have to check what those codes are, it makes the code less easy to read which is important always, and I think we are determining what image is going to be pulled from the string conditions your script provides eg "few clouds"

**Comment by sbenjam1n** [comment]
That makes sense, but those string conditions like "few clouds" are always sent with the corresponding weather ID from openweathermap, so we'll always be able to log the image description and set it as the image element's 'alt' description. Using a 20 item switch statement to translate something like clear sky to sunny-day isn't clear code.  

The IDs are always received with a description, match openweathermaps own naming scheme for their weather images and will allow the assignment of the weather image in a single line by just sticking '.png' onto it.

**Comment by damooch** [comment]
Ya that makes a lot of good sense. I see what you mean by simpler now

**Comment by sbenjam1n** [comment]
@taylorbasso This issue is resolved in my two most recent pull requests.

**Comment by taylorbasso** [comment]
@sbenjam1n Can this issue be closed, then?

**Comment by taylorbasso** [comment]
Closing
